{
	"actionTraces": [[1438247101,
	2853,
	"WebAction\/Servlet\/Proxy",
	"\/zjweb\/GPRS.do",
	"[1438247101,{},{\"httpStatus\":200,\"threadName\":\"[ACTIVE] ExecuteThread: '86' for queue: 'weblogic.kernel.Default (self-tuning)'\"},[0,2853,\"ROOT\",null,1,\"weblogic.servlet.internal.WebAppServletContext\",\"execute\",{\"stacktrace\":[\"weblogic.servlet.internal.WebAppServletContext.execute(WebAppServletContext.java:2200)\",\"weblogic.servlet.internal.ServletRequestImpl.run(ServletRequestImpl.java:1491)\",\"weblogic.work.ExecuteThread.execute(ExecuteThread.java:256)\",\"weblogic.work.ExecuteThread.run(ExecuteThread.java:221)\"]},[[0,2853,\"RequestDispatcher\\\/NULL\\\/RequestDispatcher\\\/weblogic.servlet.internal.WebAppServletContext\\\/execute\",null,1,\"weblogic.servlet.internal.WebAppServletContext\",\"execute\",{\"stacktrace\":[\"weblogic.servlet.internal.WebAppServletContext.execute(WebAppServletContext.java:2200)\",\"weblogic.servlet.internal.ServletRequestImpl.run(ServletRequestImpl.java:1491)\",\"weblogic.work.ExecuteThread.execute(ExecuteThread.java:256)\",\"weblogic.work.ExecuteThread.run(ExecuteThread.java:221)\"]},[[71,2853,\"Servlet\\\/com.zjmobile.Servlet.ProxyServlet\\\/service\",\"\",
	1,
	\"javax.servlet.http.HttpServlet\",\"service\",{\"partialtrace\":[\"javax.servlet.http.HttpServlet.service(HttpServlet.java:821)\",\"weblogic.servlet.internal.StubSecurityHelper$ServletServiceAction.run(StubSecurityHelper.java:227)\",\"weblogic.servlet.internal.StubSecurityHelper.invokeServlet(StubSecurityHelper.java:125)\",\"weblogic.servlet.internal.ServletStubImpl.execute(ServletStubImpl.java:301)\",\"weblogic.servlet.internal.ServletStubImpl.execute(ServletStubImpl.java:184)\",\"weblogic.servlet.internal.WebAppServletContext$ServletInvocationAction.wrapRun(WebAppServletContext.java:3750)\",\"weblogic.servlet.internal.WebAppServletContext$ServletInvocationAction.run(WebAppServletContext.java:3714)\",\"weblogic.security.acl.internal.AuthenticatedSubject.doAs(AuthenticatedSubject.java:321)\",\"weblogic.security.service.SecurityManager.runAs(SecurityManager.java:120)\",\"weblogic.servlet.internal.WebAppServletContext.securedExecute(WebAppServletContext.java:2283)\"]},[[73,2853,\"External\\\/http:%2F%2Fapp-mapp.yw.zj.chinamobile.com%2Fzjapp%2FGPRS.do\\\/HttpClient\\\/execute\",\"http:\\\/\\\/app-mapp.yw.zj.chinamobile.com\\\/zjapp\\\/GPRS.do\",1,\"org.apache.http.impl.client.CloseableHttpClient\",\"execute\",{\"partialtrace\":[\"org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:106)\",\"com.zjmobile.Servlet.ProxyServlet.proxy(ProxyServlet.java:75)\",\"com.zjmobile.Servlet.ProxyServlet.doPost(ProxyServlet.java:152)\",\"javax.servlet.http.HttpServlet.service(HttpServlet.java:727)\"]},[]]]]]]]]]"],
	[1438247144,
	2911,
	"WebAction\/Servlet\/Proxy",
	"\/zjweb\/SpAdvert.do",
	"[1438247144,{},{\"httpStatus\":200,\"threadName\":\"[ACTIVE] ExecuteThread: '95' for queue: 'weblogic.kernel.Default (self-tuning)'\"},[0,2912,\"ROOT\",null,1,\"weblogic.servlet.internal.WebAppServletContext\",\"execute\",{\"stacktrace\":[\"weblogic.servlet.internal.WebAppServletContext.execute(WebAppServletContext.java:2200)\",\"weblogic.servlet.internal.ServletRequestImpl.run(ServletRequestImpl.java:1491)\",\"weblogic.work.ExecuteThread.execute(ExecuteThread.java:256)\",\"weblogic.work.ExecuteThread.run(ExecuteThread.java:221)\"]},[[0,2912,\"RequestDispatcher\\\/NULL\\\/RequestDispatcher\\\/weblogic.servlet.internal.WebAppServletContext\\\/execute\",null,1,\"weblogic.servlet.internal.WebAppServletContext\",\"execute\",{\"stacktrace\":[\"weblogic.servlet.internal.WebAppServletContext.execute(WebAppServletContext.java:2200)\",\"weblogic.servlet.internal.ServletRequestImpl.run(ServletRequestImpl.java:1491)\",\"weblogic.work.ExecuteThread.execute(ExecuteThread.java:256)\",\"weblogic.work.ExecuteThread.run(ExecuteThread.java:221)\"]},[[0,2912,\"Servlet\\\/com.zjmobile.Servlet.ProxyServlet\\\/service\",\"\",
	1,
	\"javax.servlet.http.HttpServlet\",\"service\",{\"partialtrace\":[\"javax.servlet.http.HttpServlet.service(HttpServlet.java:821)\",\"weblogic.servlet.internal.StubSecurityHelper$ServletServiceAction.run(StubSecurityHelper.java:227)\",\"weblogic.servlet.internal.StubSecurityHelper.invokeServlet(StubSecurityHelper.java:125)\",\"weblogic.servlet.internal.ServletStubImpl.execute(ServletStubImpl.java:301)\",\"weblogic.servlet.internal.ServletStubImpl.execute(ServletStubImpl.java:184)\",\"weblogic.servlet.internal.WebAppServletContext$ServletInvocationAction.wrapRun(WebAppServletContext.java:3750)\",\"weblogic.servlet.internal.WebAppServletContext$ServletInvocationAction.run(WebAppServletContext.java:3714)\",\"weblogic.security.acl.internal.AuthenticatedSubject.doAs(AuthenticatedSubject.java:321)\",\"weblogic.security.service.SecurityManager.runAs(SecurityManager.java:120)\",\"weblogic.servlet.internal.WebAppServletContext.securedExecute(WebAppServletContext.java:2283)\"]},[[2,2912,\"External\\\/http:%2F%2Fapp-mapp.yw.zj.chinamobile.com%2Fzjapp%2FSpAdvert.do\\\/HttpClient\\\/execute\",\"http:\\\/\\\/app-mapp.yw.zj.chinamobile.com\\\/zjapp\\\/SpAdvert.do\",1,\"org.apache.http.impl.client.CloseableHttpClient\",\"execute\",{\"partialtrace\":[\"org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:106)\",\"com.zjmobile.Servlet.ProxyServlet.proxy(ProxyServlet.java:75)\",\"com.zjmobile.Servlet.ProxyServlet.doPost(ProxyServlet.java:152)\",\"javax.servlet.http.HttpServlet.service(HttpServlet.java:727)\"]},[]]]]]]]]]"]
	],
	"type": "actionTraceData"
}